### ISSUE TITLE
Support for the TNetHttpClient 

### ISSUE THREAD

**Issue by gmurt** [monde-sistemas/delphi-aws-ses#21]
Do you have any plans to support the NetHttpClient in Delphi XE8/Seattle instead of the Indy?

**Comment by fabioxgn** [comment]
Hi @gmurt, thanks for the interest in the project.

Right now we do not have any plans as we are still using XE7 in all our projects. But we will evaluate if the upgrade to Seattle is worth, if it is we are mostly likely to support it.

But if you'd like to use NetHttpClient, please, feel free to implement it and send a Pull Request, it is very welcome as long it does not break compatibility  with XE7.
