### ISSUE TITLE
Validate e-mail addresses

### ISSUE THREAD

**Issue by martinusso** [monde-sistemas/delphi-aws-ses#22]
In case of e-mail addresses invalid the following error occurs:

```
HTTP/1.1 400 Bad Request - Domain contains control or whitespace (InvalidParameterValue)
```

Validate the fields `FromAddress`, `Recipients`, `ReplyTo`, `CC` and `BCC` and return a improved message before sending emails.

**Comment by esasse** [comment]
I'm not sure if we should validate. I like the idea of leaving all
validation to AWS.

Any particular reason you think we should validate?

**Comment by martinusso** [comment]
I thought I'd improve this return message, because currently we don't know even what field is invalid.
But it really makes more sense to leave the responsibility to AWS. tks!
