### ISSUE TITLE
Incompatible with Delphi Berlin 10.1

### ISSUE THREAD

**Issue by mcirinei** [monde-sistemas/delphi-aws-ses#24]
The library doesn't compile on Berlin (SignString parameters not compatible)

**Comment by fabioxgn** [comment]
@mcirinei hello. Thanks for the interest in our library. Right now we only use XE7, but feel free to fix it for Berlin and send us a PR, it will be very appreciated. Thanks.

**Comment by fabioxgn** [comment]
The library supports Delphi up until Tokyo now.
