### ISSUE TITLE
Assert query parameters values

### ISSUE THREAD

**Issue by martinusso** [monde-sistemas/delphi-aws-ses#7]
The query parameters values aren't checked. It could be implemented in the BuildQueryParameters class.

**Comment by esasse** [comment]
This issue is not clear to me. What do you mean?

**Comment by martinusso** [comment]
For example, if a recipient has been informed blank, this value is not handled in the library. Only in the Post method, that returns an error:

`HTTP/1.1 400 Bad Request - 1 validation error detected: Value null at ''destination'' failed to satisfy constraint: Member must not be null (ValidationError)`

**Comment by esasse** [comment]
Since the API is returning a good and detailed error message, I don't think we need to duplicate the validation logic here.
